/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SecureChain {
  export type AssetStruct = {
    tokenId: BigNumberish;
    assetId: string;
    name: string;
    description: string;
    category: string;
    metadataURI: string;
    creator: AddressLike;
    currentOwner: AddressLike;
    createdAt: BigNumberish;
    status: BigNumberish;
    mintTxHash: string;
  };

  export type AssetStructOutput = [
    tokenId: bigint,
    assetId: string,
    name: string,
    description: string,
    category: string,
    metadataURI: string,
    creator: string,
    currentOwner: string,
    createdAt: bigint,
    status: bigint,
    mintTxHash: string
  ] & {
    tokenId: bigint;
    assetId: string;
    name: string;
    description: string;
    category: string;
    metadataURI: string;
    creator: string;
    currentOwner: string;
    createdAt: bigint;
    status: bigint;
    mintTxHash: string;
  };

  export type AuditRecordStruct = {
    auditId: BigNumberish;
    actor: AddressLike;
    action: string;
    resourceType: string;
    resourceId: string;
    role: BytesLike;
    txHash: string;
    blockNumber: BigNumberish;
    timestamp: BigNumberish;
    verified: boolean;
  };

  export type AuditRecordStructOutput = [
    auditId: bigint,
    actor: string,
    action: string,
    resourceType: string,
    resourceId: string,
    role: string,
    txHash: string,
    blockNumber: bigint,
    timestamp: bigint,
    verified: boolean
  ] & {
    auditId: bigint;
    actor: string;
    action: string;
    resourceType: string;
    resourceId: string;
    role: string;
    txHash: string;
    blockNumber: bigint;
    timestamp: bigint;
    verified: boolean;
  };

  export type IdentityStruct = {
    did: string;
    wallet: AddressLike;
    identityHash: BytesLike;
    verified: boolean;
    createdAt: BigNumberish;
    verifiedAt: BigNumberish;
    verificationTxHash: string;
  };

  export type IdentityStructOutput = [
    did: string,
    wallet: string,
    identityHash: string,
    verified: boolean,
    createdAt: bigint,
    verifiedAt: bigint,
    verificationTxHash: string
  ] & {
    did: string;
    wallet: string;
    identityHash: string;
    verified: boolean;
    createdAt: bigint;
    verifiedAt: bigint;
    verificationTxHash: string;
  };
}

export interface SecureChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "AUDITOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "IDENTITY_VERIFIER_ROLE"
      | "MANAGER_ROLE"
      | "MINTER_ROLE"
      | "allocateAsset"
      | "approve"
      | "assetTransferHistory"
      | "assets"
      | "assignRole"
      | "auditRecords"
      | "balanceOf"
      | "burnAsset"
      | "createIdentity"
      | "didExists"
      | "freezeAsset"
      | "getApproved"
      | "getAsset"
      | "getAssetTransferHistory"
      | "getAssetsByCategory"
      | "getAuditCount"
      | "getAuditRecord"
      | "getIdentity"
      | "getRoleAdmin"
      | "getUserAssets"
      | "getUserDIDs"
      | "grantRole"
      | "hasRole"
      | "identities"
      | "isApprovedForAll"
      | "mintAsset"
      | "name"
      | "ownerOf"
      | "renounceRole"
      | "revokeRole"
      | "revokeRoleFromAccount"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "supportsInterface"
      | "symbol"
      | "tokenURI"
      | "transferAsset"
      | "transferFrom"
      | "unfreezeAsset"
      | "userAssets"
      | "userDIDs"
      | "verifyIdentity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "AssetAllocated"
      | "AssetMinted"
      | "AssetTransferred"
      | "AuditRecorded"
      | "BatchMetadataUpdate"
      | "IdentityCreated"
      | "IdentityVerified"
      | "MetadataUpdate"
      | "RoleAdminChanged"
      | "RoleAssigned"
      | "RoleGranted"
      | "RoleRevoked"
      | "RoleRevokedCustom"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IDENTITY_VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allocateAsset",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assetTransferHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignRole",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "auditRecords",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "burnAsset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createIdentity",
    values: [string, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "didExists", values: [string]): string;
  encodeFunctionData(
    functionFragment: "freezeAsset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAsset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetTransferHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetsByCategory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getIdentity", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAssets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDIDs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "identities", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintAsset",
    values: [string, string, string, string, string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRoleFromAccount",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAsset",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezeAsset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userAssets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userDIDs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyIdentity",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IDENTITY_VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocateAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetTransferHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assignRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "auditRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burnAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "didExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "freezeAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAssetTransferHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetsByCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "identities", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintAsset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeRoleFromAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezeAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userAssets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userDIDs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyIdentity",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetAllocatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    from: string,
    to: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    from: string;
    to: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    assetId: string,
    creator: AddressLike,
    owner: AddressLike,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    assetId: string,
    creator: string,
    owner: string,
    name: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    assetId: string;
    creator: string;
    owner: string;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetTransferredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    from: string,
    to: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    from: string;
    to: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditRecordedEvent {
  export type InputTuple = [
    auditId: BigNumberish,
    actor: AddressLike,
    action: string,
    resourceType: string,
    resourceId: string,
    role: BytesLike,
    blockNumber: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    auditId: bigint,
    actor: string,
    action: string,
    resourceType: string,
    resourceId: string,
    role: string,
    blockNumber: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    auditId: bigint;
    actor: string;
    action: string;
    resourceType: string;
    resourceId: string;
    role: string;
    blockNumber: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchMetadataUpdateEvent {
  export type InputTuple = [
    _fromTokenId: BigNumberish,
    _toTokenId: BigNumberish
  ];
  export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
  export interface OutputObject {
    _fromTokenId: bigint;
    _toTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityCreatedEvent {
  export type InputTuple = [
    did: string,
    wallet: AddressLike,
    identityHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    did: string,
    wallet: string,
    identityHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    did: string;
    wallet: string;
    identityHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityVerifiedEvent {
  export type InputTuple = [
    did: string,
    verifier: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [did: string, verifier: string, timestamp: bigint];
  export interface OutputObject {
    did: string;
    verifier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdateEvent {
  export type InputTuple = [_tokenId: BigNumberish];
  export type OutputTuple = [_tokenId: bigint];
  export interface OutputObject {
    _tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAssignedEvent {
  export type InputTuple = [
    account: AddressLike,
    role: BytesLike,
    assigner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    role: string,
    assigner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    account: string;
    role: string;
    assigner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedCustomEvent {
  export type InputTuple = [
    account: AddressLike,
    role: BytesLike,
    revoker: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    role: string,
    revoker: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    account: string;
    role: string;
    revoker: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecureChain extends BaseContract {
  connect(runner?: ContractRunner | null): SecureChain;
  waitForDeployment(): Promise<this>;

  interface: SecureChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  AUDITOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  IDENTITY_VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  MINTER_ROLE: TypedContractMethod<[], [string], "view">;

  allocateAsset: TypedContractMethod<
    [tokenId: BigNumberish, to: AddressLike],
    [boolean],
    "nonpayable"
  >;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  assetTransferHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  assets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string
      ] & {
        tokenId: bigint;
        assetId: string;
        name: string;
        description: string;
        category: string;
        metadataURI: string;
        creator: string;
        currentOwner: string;
        createdAt: bigint;
        status: bigint;
        mintTxHash: string;
      }
    ],
    "view"
  >;

  assignRole: TypedContractMethod<
    [account: AddressLike, role: BytesLike],
    [boolean],
    "nonpayable"
  >;

  auditRecords: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        auditId: bigint;
        actor: string;
        action: string;
        resourceType: string;
        resourceId: string;
        role: string;
        txHash: string;
        blockNumber: bigint;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  burnAsset: TypedContractMethod<
    [tokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  createIdentity: TypedContractMethod<
    [did: string, wallet: AddressLike, identityHash: BytesLike],
    [boolean],
    "nonpayable"
  >;

  didExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  freezeAsset: TypedContractMethod<
    [tokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getAsset: TypedContractMethod<
    [tokenId: BigNumberish],
    [SecureChain.AssetStructOutput],
    "view"
  >;

  getAssetTransferHistory: TypedContractMethod<
    [tokenId: BigNumberish],
    [string[]],
    "view"
  >;

  getAssetsByCategory: TypedContractMethod<
    [category: string],
    [bigint[]],
    "view"
  >;

  getAuditCount: TypedContractMethod<[], [bigint], "view">;

  getAuditRecord: TypedContractMethod<
    [auditId: BigNumberish],
    [SecureChain.AuditRecordStructOutput],
    "view"
  >;

  getIdentity: TypedContractMethod<
    [did: string],
    [SecureChain.IdentityStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getUserAssets: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getUserDIDs: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  identities: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, bigint, bigint, string] & {
        did: string;
        wallet: string;
        identityHash: string;
        verified: boolean;
        createdAt: bigint;
        verifiedAt: bigint;
        verificationTxHash: string;
      }
    ],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  mintAsset: TypedContractMethod<
    [
      assetId: string,
      name: string,
      description: string,
      category: string,
      metadataURI: string,
      initialOwner: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRoleFromAccount: TypedContractMethod<
    [account: AddressLike, role: BytesLike],
    [boolean],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferAsset: TypedContractMethod<
    [tokenId: BigNumberish, to: AddressLike],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unfreezeAsset: TypedContractMethod<
    [tokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  userAssets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userDIDs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  verifyIdentity: TypedContractMethod<[did: string], [boolean], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "AUDITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "IDENTITY_VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MINTER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allocateAsset"
  ): TypedContractMethod<
    [tokenId: BigNumberish, to: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assetTransferHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "assets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string
      ] & {
        tokenId: bigint;
        assetId: string;
        name: string;
        description: string;
        category: string;
        metadataURI: string;
        creator: string;
        currentOwner: string;
        createdAt: bigint;
        status: bigint;
        mintTxHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "assignRole"
  ): TypedContractMethod<
    [account: AddressLike, role: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "auditRecords"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        auditId: bigint;
        actor: string;
        action: string;
        resourceType: string;
        resourceId: string;
        role: string;
        txHash: string;
        blockNumber: bigint;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "burnAsset"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "createIdentity"
  ): TypedContractMethod<
    [did: string, wallet: AddressLike, identityHash: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "didExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "freezeAsset"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getAsset"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [SecureChain.AssetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAssetTransferHistory"
  ): TypedContractMethod<[tokenId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAssetsByCategory"
  ): TypedContractMethod<[category: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getAuditCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAuditRecord"
  ): TypedContractMethod<
    [auditId: BigNumberish],
    [SecureChain.AuditRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIdentity"
  ): TypedContractMethod<
    [did: string],
    [SecureChain.IdentityStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserAssets"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserDIDs"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "identities"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, bigint, bigint, string] & {
        did: string;
        wallet: string;
        identityHash: string;
        verified: boolean;
        createdAt: bigint;
        verifiedAt: bigint;
        verificationTxHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintAsset"
  ): TypedContractMethod<
    [
      assetId: string,
      name: string,
      description: string,
      category: string,
      metadataURI: string,
      initialOwner: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRoleFromAccount"
  ): TypedContractMethod<
    [account: AddressLike, role: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferAsset"
  ): TypedContractMethod<
    [tokenId: BigNumberish, to: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unfreezeAsset"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "userAssets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userDIDs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyIdentity"
  ): TypedContractMethod<[did: string], [boolean], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "AssetAllocated"
  ): TypedContractEvent<
    AssetAllocatedEvent.InputTuple,
    AssetAllocatedEvent.OutputTuple,
    AssetAllocatedEvent.OutputObject
  >;
  getEvent(
    key: "AssetMinted"
  ): TypedContractEvent<
    AssetMintedEvent.InputTuple,
    AssetMintedEvent.OutputTuple,
    AssetMintedEvent.OutputObject
  >;
  getEvent(
    key: "AssetTransferred"
  ): TypedContractEvent<
    AssetTransferredEvent.InputTuple,
    AssetTransferredEvent.OutputTuple,
    AssetTransferredEvent.OutputObject
  >;
  getEvent(
    key: "AuditRecorded"
  ): TypedContractEvent<
    AuditRecordedEvent.InputTuple,
    AuditRecordedEvent.OutputTuple,
    AuditRecordedEvent.OutputObject
  >;
  getEvent(
    key: "BatchMetadataUpdate"
  ): TypedContractEvent<
    BatchMetadataUpdateEvent.InputTuple,
    BatchMetadataUpdateEvent.OutputTuple,
    BatchMetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "IdentityCreated"
  ): TypedContractEvent<
    IdentityCreatedEvent.InputTuple,
    IdentityCreatedEvent.OutputTuple,
    IdentityCreatedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityVerified"
  ): TypedContractEvent<
    IdentityVerifiedEvent.InputTuple,
    IdentityVerifiedEvent.OutputTuple,
    IdentityVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdate"
  ): TypedContractEvent<
    MetadataUpdateEvent.InputTuple,
    MetadataUpdateEvent.OutputTuple,
    MetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAssigned"
  ): TypedContractEvent<
    RoleAssignedEvent.InputTuple,
    RoleAssignedEvent.OutputTuple,
    RoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevokedCustom"
  ): TypedContractEvent<
    RoleRevokedCustomEvent.InputTuple,
    RoleRevokedCustomEvent.OutputTuple,
    RoleRevokedCustomEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "AssetAllocated(uint256,address,address,uint256)": TypedContractEvent<
      AssetAllocatedEvent.InputTuple,
      AssetAllocatedEvent.OutputTuple,
      AssetAllocatedEvent.OutputObject
    >;
    AssetAllocated: TypedContractEvent<
      AssetAllocatedEvent.InputTuple,
      AssetAllocatedEvent.OutputTuple,
      AssetAllocatedEvent.OutputObject
    >;

    "AssetMinted(uint256,string,address,address,string,uint256)": TypedContractEvent<
      AssetMintedEvent.InputTuple,
      AssetMintedEvent.OutputTuple,
      AssetMintedEvent.OutputObject
    >;
    AssetMinted: TypedContractEvent<
      AssetMintedEvent.InputTuple,
      AssetMintedEvent.OutputTuple,
      AssetMintedEvent.OutputObject
    >;

    "AssetTransferred(uint256,address,address,uint256)": TypedContractEvent<
      AssetTransferredEvent.InputTuple,
      AssetTransferredEvent.OutputTuple,
      AssetTransferredEvent.OutputObject
    >;
    AssetTransferred: TypedContractEvent<
      AssetTransferredEvent.InputTuple,
      AssetTransferredEvent.OutputTuple,
      AssetTransferredEvent.OutputObject
    >;

    "AuditRecorded(uint256,address,string,string,string,bytes32,uint256,uint256)": TypedContractEvent<
      AuditRecordedEvent.InputTuple,
      AuditRecordedEvent.OutputTuple,
      AuditRecordedEvent.OutputObject
    >;
    AuditRecorded: TypedContractEvent<
      AuditRecordedEvent.InputTuple,
      AuditRecordedEvent.OutputTuple,
      AuditRecordedEvent.OutputObject
    >;

    "BatchMetadataUpdate(uint256,uint256)": TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;
    BatchMetadataUpdate: TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;

    "IdentityCreated(string,address,bytes32,uint256)": TypedContractEvent<
      IdentityCreatedEvent.InputTuple,
      IdentityCreatedEvent.OutputTuple,
      IdentityCreatedEvent.OutputObject
    >;
    IdentityCreated: TypedContractEvent<
      IdentityCreatedEvent.InputTuple,
      IdentityCreatedEvent.OutputTuple,
      IdentityCreatedEvent.OutputObject
    >;

    "IdentityVerified(string,address,uint256)": TypedContractEvent<
      IdentityVerifiedEvent.InputTuple,
      IdentityVerifiedEvent.OutputTuple,
      IdentityVerifiedEvent.OutputObject
    >;
    IdentityVerified: TypedContractEvent<
      IdentityVerifiedEvent.InputTuple,
      IdentityVerifiedEvent.OutputTuple,
      IdentityVerifiedEvent.OutputObject
    >;

    "MetadataUpdate(uint256)": TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;
    MetadataUpdate: TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleAssigned(address,bytes32,address,uint256)": TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;
    RoleAssigned: TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "RoleRevokedCustom(address,bytes32,address,uint256)": TypedContractEvent<
      RoleRevokedCustomEvent.InputTuple,
      RoleRevokedCustomEvent.OutputTuple,
      RoleRevokedCustomEvent.OutputObject
    >;
    RoleRevokedCustom: TypedContractEvent<
      RoleRevokedCustomEvent.InputTuple,
      RoleRevokedCustomEvent.OutputTuple,
      RoleRevokedCustomEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
